### ISSUE TITLE
Documentation possibly missing install of a dependency when building

### ISSUE THREAD

**Issue by jdeisenberg** [Courseography/courseography#1002]
Following the guidelines in the wiki and in the README.md, I did these commands, with all steps successful except the last, which gives the following error:

````
> git clone https://github.com/Courseography/courseography.git
> cd courseography
> mkdir db
> cp app/DevelopmentConfig.hs app/Config.hs
> stack setup
> stack build
> stack exec courseography graphs
> stack exec courseography database
> stack exec courseography css
> stack exec courseography
courseography: node_modules/.bin/webpack: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
````

**Comment by abrarisme** [comment]
Ran into the same issue, and including details in case someone has this problem.   

If you check out the [setup script](https://github.com/Courseography/courseography/blob/master/scripts/setup_linux), you can see that it's using `yarn` instead of `npm` as the package manager. You just need to run `yarn install` (assuming you have it downloaded) inside the package.
