### ISSUE TITLE
Check for accessibility issues

### ISSUE THREAD

**Issue by pgries** [Courseography/courseography#301]
Find out how to check whether the site is accessible for colour blindness and other visual issues.

**Comment by jmatholia** [comment]
I think this will be interesting!

**Comment by david-yz-liu** [comment]
@jmatholia Okay, you've been assigned! Please post what resources you find over here.

**Comment by jmatholia** [comment]
For now I am trying these two:
http://www.color-blindness.com/coblis-color-blindness-simulator/
http://colororacle.org/index.html
These are both simulators the first online and the latter a download. I am not sure if that is what we were looking for, or if there are websites that actually measure a website's accessibility. Let me know. Would you like me to post pictures here or present the options on Monday?

**Comment by david-yz-liu** [comment]
These tools seem like what @pgries was asking for. It would be great if you could post pictures here.

**Comment by pgries** [comment]
I think these are good tools to use.  How does the colour scheme for the prerequisite chart look in these?

**Comment by jmatholia** [comment]
Normal Vision:
![image](https://cloud.githubusercontent.com/assets/9491656/5989243/814aca0e-a94e-11e4-90c6-e7d72d825d5c.png)

Deuteranopia (most common):
![image](https://cloud.githubusercontent.com/assets/9491656/5989927/2f65de9a-a967-11e4-8ce6-d2c8b0999148.png)

Protanopia (rare):
![image](https://cloud.githubusercontent.com/assets/9491656/5989929/4e31c5e6-a967-11e4-91b7-6d83cf352af1.png)

Tritanopia (very rare):
![image](https://cloud.githubusercontent.com/assets/9491656/5989931/65ea6418-a967-11e4-8b44-d2b63d058961.png)

Note in the first two how the red outlines that should be around the subjects with unsatisfied pre-requisites are almost invisible. Also when the hovering over a course, the arrows and courses that should turn red for unsatisfied pre-reqs are also almost invisible. 

![image](https://cloud.githubusercontent.com/assets/9491656/5989954/607f3bec-a968-11e4-86ed-3b5305d823f9.png)

Higher contrast between the Theory group's background and the white might be nice. And some of the groups have very similar background colours, but they can be separated so that's not as big of an issue.

**Comment by pgries** [comment]
Nice!  I think that there is enough contrast between adjacent areas that we're in good shape.

**Comment by Ian-Stewart-Binks** [comment]
It doesn't look like the initial image has the new opacity changes (Although, I may be mistaken). The opacity changes might make some colours more subtle. @jmatholia Does this have a noticeable affect on the output?

**Comment by jmatholia** [comment]
Yes you are right the normal vision graph doesn't have the opacity changes but I realized this and made the changes to my drawing branch since I was having that issue with the happstack one. So the filtered images are actually done with the lower opacity, I just forgot to replace the normal vision screenshot.
