### ISSUE TITLE
JavaScript 'Areas'

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#378]
In create_data.js, the variable `areas` is no longer necessary. Every node has their data-group assigned in the generation process.

**Comment by christinem** [comment]
I am actually using this now in Check My Post in order to fill the active courses. If it's not used anywhere else now though, I could just make an array of all CSC courses in the graph - the significance of areas is not important for me, I was just trying to avoid creating an extra array. What do you think?

**Comment by Ian-Stewart-Binks** [comment]
@christinem Each node in the graph should have an attribute with its area.

**Comment by christinem** [comment]
@Ian-Stewart-Binks I agree. Like I said the purpose of me using areas was to avoid creating a new array, but in this situation since areas is not used anymore now we can just replace it with an array of all courses. I can change this.
