### ISSUE TITLE
Draw: Moving Region

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#518]
The behaviour for moving a region is a bit off.

**Comment by arkon** [comment]
In `getClickPosition` in [draw.js](https://github.com/Courseography/courseography/blob/master/public/js/draw/draw.js), I think removing  the `parentPosition` stuff fixes this issue.

I'm not super familiar with the code base though, so I might be wrong, since I'm just basing it off of playing around with the code in Chrome Dev Tools.
